import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'OAS-UI',
  description: '框架无关的 Web Components UI 组件库',
  lang: 'zh-CN',
  themeConfig: {
    nav: [{ text: '指南', link: '/guide/getting-started' }],
    sidebar: [
      {
        text: '指南',
        items: [
          { text: '快速开始', link: '/guide/getting-started' },
          { text: '主题与自定义', link: '/guide/theming' },
          { text: '无障碍（A11y）', link: '/guide/accessibility' },
        ],
      },
      {
        text: '基础组件',
        items: [
          { text: 'Button 按钮', link: '/components/button' },
          { text: 'Icon 图标', link: '/components/icon' },
          { text: 'Tag 标签', link: '/components/tag' },
          { text: 'Badge 徽标', link: '/components/badge' },
          { text: 'Space 间距', link: '/components/space' },
          { text: 'Divider 分割线', link: '/components/divider' },
          { text: 'Link 链接', link: '/components/link' },
          { text: 'Typography 排版', link: '/components/typography' },
        ],
      },
      {
        text: '表单组件',
        items: [
          { text: 'Input 输入框', link: '/components/input' },
          { text: 'Textarea 文本域', link: '/components/textarea' },
          { text: 'Checkbox 复选框', link: '/components/checkbox' },
          { text: 'Radio 单选框', link: '/components/radio' },
          { text: 'Switch 开关', link: '/components/switch' },
          { text: 'Slider 滑块', link: '/components/slider' },
          { text: 'InputNumber 数字输入', link: '/components/input-number' },
          { text: 'Rate 评分', link: '/components/rate' },
          { text: 'Select 选择器', link: '/components/select' },
          { text: 'AutoComplete 自动完成', link: '/components/auto-complete' },
          { text: 'Cascader 级联选择', link: '/components/cascader' },
          { text: 'TreeSelect 树选择', link: '/components/tree-select' },
          { text: 'Form 表单', link: '/components/form' },
        ],
      },
      {
        text: '反馈组件',
        collapsed: true,
        items: [
            { text: 'Message 消息提示', link: '/components/message' },
            { text: 'Notification 通知', link: '/components/notification' },
            { text: 'Modal 对话框', link: '/components/modal' },
            { text: 'Confirm 确认框', link: '/components/confirm' },
            { text: 'Drawer 抽屉', link: '/components/drawer' },
            { text: 'Popconfirm 气泡确认', link: '/components/popconfirm' },
            { text: 'Alert 警告提示', link: '/components/alert' },
            { text: 'Progress 进度条', link: '/components/progress' },
            { text: 'LoadingBar 顶部加载', link: '/components/loading-bar' },
            { text: 'Spin 加载中', link: '/components/spin' },
            { text: 'Skeleton 骨架屏', link: '/components/skeleton' },
            { text: 'Empty 空状态', link: '/components/empty' },
            { text: 'Result 结果页', link: '/components/result' },
          ],
        },
        {
          text: '导航与浮层组件',
          collapsed: true,
          items: [
            { text: 'Tooltip 文字提示', link: '/components/tooltip' },
            { text: 'Popover 气泡卡片', link: '/components/popover' },
            { text: 'Menu 菜单', link: '/components/menu' },
            { text: 'Dropdown 下拉菜单', link: '/components/dropdown' },
            { text: 'ContextMenu 右键菜单', link: '/components/context-menu' },
            { text: 'HoverCard 悬停卡片', link: '/components/hover-card' },
            { text: 'Breadcrumb 面包屑', link: '/components/breadcrumb' },
            { text: 'Anchor 锚点', link: '/components/anchor' },
            { text: 'BackTop 回到顶部', link: '/components/back-top' },
            { text: 'Tour 引导', link: '/components/tour' },
          ],
        },
        {
          text: '导航与布局组件',
          collapsed: true,
          items: [
            { text: 'Tabs 标签页', link: '/components/tabs' },
            { text: 'Pagination 分页', link: '/components/pagination' },
            { text: 'Steps 步骤条', link: '/components/steps' },
            { text: 'Segmented 分段器', link: '/components/segmented' },
            { text: 'Affix 固钉', link: '/components/affix' },
            { text: 'Splitter 分割面板', link: '/components/splitter' },
            { text: 'Flex 弹性布局', link: '/components/flex' },
            { text: 'PageHeader 页头', link: '/components/page-header' },
            { text: 'FloatButton 悬浮按钮', link: '/components/float-button' },
            { text: 'Layout 布局', link: '/components/layout' },
            { text: 'Grid 栅格', link: '/components/grid' },
          ],
        },
        {
          text: '数据展示组件',
          collapsed: true,
          items: [
            { text: 'Table 表格', link: '/components/table' },
            { text: 'Tree 树', link: '/components/tree' },
            { text: 'Card 卡片', link: '/components/card' },
            { text: 'Avatar 头像', link: '/components/avatar' },
            { text: 'Image 图片', link: '/components/image' },
            { text: 'Collapse 折叠面板', link: '/components/collapse' },
            { text: 'Descriptions 描述列表', link: '/components/descriptions' },
            { text: 'Timeline 时间线', link: '/components/timeline' },
            { text: 'List 列表', link: '/components/list' },
            { text: 'Carousel 轮播', link: '/components/carousel' },
          ],
        },
    ],
  },
})
