import { alertCirclePath, arrowDownPath, arrowLeftPath, arrowRightPath, arrowUpPath, calendarPath, checkCirclePath, checkPath, chevronDownPath, chevronLeftPath, chevronRightPath, chevronUpPath, clockPath, closeCirclePath, closePath, copyPath, downloadPath, editPath, errorPath, externalLinkPath, eyePath, filterPath, gearPath, heartPath, infoPath, loadingPath, lockPath, mailPath, menuPath, minusPath, moreVerticalPath, morePath, plusPath, refreshPath, searchPath, sortPath, starFilledPath, starPath, trashPath, uploadPath, userPath, warningPath } from './icons/index.js'

export const iconRegistry = {
  'alert-circle': alertCirclePath,
  'arrow-down': arrowDownPath,
  'arrow-left': arrowLeftPath,
  'arrow-right': arrowRightPath,
  'arrow-up': arrowUpPath,
  'calendar': calendarPath,
  'check-circle': checkCirclePath,
  'check': checkPath,
  'chevron-down': chevronDownPath,
  'chevron-left': chevronLeftPath,
  'chevron-right': chevronRightPath,
  'chevron-up': chevronUpPath,
  'clock': clockPath,
  'close-circle': closeCirclePath,
  'close': closePath,
  'copy': copyPath,
  'download': downloadPath,
  'edit': editPath,
  'error': errorPath,
  'external-link': externalLinkPath,
  'eye': eyePath,
  'filter': filterPath,
  'gear': gearPath,
  'heart': heartPath,
  'info': infoPath,
  'loading': loadingPath,
  'lock': lockPath,
  'mail': mailPath,
  'menu': menuPath,
  'minus': minusPath,
  'more-vertical': moreVerticalPath,
  'more': morePath,
  'plus': plusPath,
  'refresh': refreshPath,
  'search': searchPath,
  'sort': sortPath,
  'star-filled': starFilledPath,
  'star': starPath,
  'trash': trashPath,
  'upload': uploadPath,
  'user': userPath,
  'warning': warningPath,
} as const

export type IconName = keyof typeof iconRegistry

export const iconNames: readonly IconName[] = [
  "alert-circle",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "calendar",
  "check-circle",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "clock",
  "close-circle",
  "close",
  "copy",
  "download",
  "edit",
  "error",
  "external-link",
  "eye",
  "filter",
  "gear",
  "heart",
  "info",
  "loading",
  "lock",
  "mail",
  "menu",
  "minus",
  "more-vertical",
  "more",
  "plus",
  "refresh",
  "search",
  "sort",
  "star-filled",
  "star",
  "trash",
  "upload",
  "user",
  "warning"
] as const
