/**
 * 表单 族注册入口（CDN 按需打包产物 dist/cdn/form.js）。
 * 基座内联：@oas-ui/i18n + config-provider/app/theme-editor 框架级三件（每族都 import，幂等守卫防重）。
 * 族内容 = 源码顶层目录「表单」全部组件 index.js（import 即注册，与 src/index.ts 的 表单 段一致）。
 * 纯 import 组装，无执行逻辑。
 */
import '@oas-ui/i18n'
import '../framework/config-provider/index.js'
import '../framework/app/index.js'
import '../framework/theme-editor/index.js'
import '../form/input/index.js'
import '../form/textarea/index.js'
import '../form/checkbox/index.js'
import '../form/radio/index.js'
import '../form/switch/index.js'
import '../form/slider/index.js'
import '../form/input-number/index.js'
import '../form/rate/index.js'
import '../form/select/index.js'
import '../form/auto-complete/index.js'
import '../form/combobox/index.js'
import '../form/cascader/index.js'
import '../form/tree-select/index.js'
import '../form/mentions/index.js'
import '../form/form/index.js'
import '../form/form-item/index.js'
import '../form/calendar/index.js'
import '../form/date-picker/index.js'
import '../form/time-picker/index.js'
import '../form/upload/index.js'
import '../form/transfer/index.js'
import '../form/color-picker/index.js'
import '../form/toggle-button/index.js'
import '../form/toggle-group/index.js'
import '../form/pin-input/index.js'
import '../form/dynamic-input/index.js'
import '../form/dynamic-tags/index.js'
import '../form/editable/index.js'
import '../form/segmented/index.js'
